import { Role } from "@prisma/client";

export const permissionKeys = {
  dashboardRead: "dashboard.read",
  equipmentRead: "equipment.read",
  equipmentManage: "equipment.manage",
  entryRead: "entry.read",
  entryCreate: "entry.create",
  entryApprove: "entry.approve",
  planRead: "plan.read",
  checksheetRead: "checksheet.read",
  checksheetIssue: "checksheet.issue",
  checksheetComplete: "checksheet.complete",
  alertsRead: "alerts.read",
  alertsAcknowledge: "alerts.acknowledge",
  notificationsRead: "notifications.read",
  notificationsManage: "notifications.manage",
  escalationRun: "escalation.run",
  forecastDriftRead: "forecast.drift.read",
  usersRead: "users.read",
  usersManage: "users.manage",
  permissionsManage: "permissions.manage",
} as const;

export const roleDefaultPermissions: Record<Role, string[]> = {
  USER: [
    permissionKeys.dashboardRead,
    permissionKeys.equipmentRead,
    permissionKeys.entryRead,
    permissionKeys.entryCreate,
    permissionKeys.planRead,
    permissionKeys.checksheetRead,
    permissionKeys.alertsRead,
    permissionKeys.alertsAcknowledge,
    permissionKeys.notificationsRead,
    permissionKeys.notificationsManage,
    permissionKeys.forecastDriftRead,
  ],
  ADMIN: [
    permissionKeys.dashboardRead,
    permissionKeys.equipmentRead,
    permissionKeys.equipmentManage,
    permissionKeys.entryRead,
    permissionKeys.entryCreate,
    permissionKeys.entryApprove,
    permissionKeys.planRead,
    permissionKeys.checksheetRead,
    permissionKeys.checksheetIssue,
    permissionKeys.checksheetComplete,
    permissionKeys.alertsRead,
    permissionKeys.alertsAcknowledge,
    permissionKeys.notificationsRead,
    permissionKeys.notificationsManage,
    permissionKeys.escalationRun,
    permissionKeys.forecastDriftRead,
  ],
  SUPERADMIN: Object.values(permissionKeys),
};

export const permissionCatalog = [
  { key: permissionKeys.dashboardRead, name: "Read Dashboard" },
  { key: permissionKeys.equipmentRead, name: "Read Equipment" },
  { key: permissionKeys.equipmentManage, name: "Manage Equipment" },
  { key: permissionKeys.entryRead, name: "Read Entries" },
  { key: permissionKeys.entryCreate, name: "Create Entries" },
  { key: permissionKeys.entryApprove, name: "Approve Entries" },
  { key: permissionKeys.planRead, name: "Read Planning" },
  { key: permissionKeys.checksheetRead, name: "Read Checksheets" },
  { key: permissionKeys.checksheetIssue, name: "Issue Checksheets" },
  { key: permissionKeys.checksheetComplete, name: "Complete Checksheets" },
  { key: permissionKeys.alertsRead, name: "Read Alerts" },
  { key: permissionKeys.alertsAcknowledge, name: "Acknowledge Alerts" },
  { key: permissionKeys.notificationsRead, name: "Read Notifications" },
  { key: permissionKeys.notificationsManage, name: "Manage Notifications" },
  { key: permissionKeys.escalationRun, name: "Run Escalation" },
  { key: permissionKeys.forecastDriftRead, name: "Read Forecast Drift" },
  { key: permissionKeys.usersRead, name: "Read Users" },
  { key: permissionKeys.usersManage, name: "Manage Users" },
  { key: permissionKeys.permissionsManage, name: "Manage Permissions" },
];
